add classes for every struct or enum, fix typos
Kuama-IT/just_audio pull request #6
Opened 2022-08-22 15:25 UTC by GabM3

add custom error classes and delete the static functions used to throw them

2022-08-22 16:02 UTC, SimoneBressan submitted a review, later dismissed

2022-08-23 07:44 UTC, kuamanet requested changes

2022-08-23 07:44 UTC, kuamanet commented on just_audio/darwin/Classes/Player.swift
> +    func _resume() {
Drop the undescore

2022-08-23 08:36 UTC, SimoneBressan approved these changes, later dismissed

2022-08-23 11:17 UTC, kuamanet approved these changes

2022-08-23 12:59 UTC, SimoneBressan approved these changes

2022-08-23 13:23 UTC, merged